# Projekt-Identifier in SonarQube
sonar.projectKey=activate

# Projektname (wird im Dashboard angezeigt)
sonar.projectName=ACTIVATE

# Quellcode-Ordner (relativ zum Projektroot)
sonar.sources=src

# Encoding der Quellcodedateien
sonar.sourceEncoding=UTF-8

# Pfad zur TypeScript-Konfigurationsdatei
sonar.typescript.tsconfigPath=tsconfig.json

# Coverage-Report-Pfad (wenn Tests mit Coverage)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Dateien/Ordner ausschließen (Tests, node_modules, Build-Ordner)
sonar.exclusions=**/*.spec.ts,**/node_modules/**,dist/**

# Authentifizierungstoken (ersetze durch deinen Token)
sonar.login=squ_a672260147595101ba661a1df0d9d3355cf12d17